[분할 정복] 10월 11일
Altu-Bitu/Altu-Bitu_jaeseo pull request #12
Opened 2021-10-10 17:22 UTC by jaeseo222

감사합니다........!!!!!!!!!!!!!!!

2021-10-11 09:26 UTC, bsa0322 requested changes
p1. 잘 풀어주셨네요!! 주석 설명이 자세해서 너무 좋았어요. 17281에 p1붙은 코멘트는 꼭 수정해주세요! 다른 부분도 수정해보셔도 좋아요. 수정 후 저 리뷰어로 호출해주세요! 수고하셨습니다~~!!!

2021-10-11 09:26 UTC, bsa0322 commented on 10월 5일 - 분할 정복/1074.cpp
> +	// + 반대로 1사분면에 있다면 2사분면이나 3사분면을 분할하지 않아도 된다.
👍👍👍

2021-10-11 09:26 UTC, bsa0322 commented on 10월 5일 - 분할 정복/1074.cpp
> +	}
p2. 이 부분은 없어도 괜찮겠네요! 왜 그럴까요? (32-35번째 줄을 주목해주세요!)

2021-10-11 09:26 UTC, bsa0322 commented on 10월 5일 - 분할 정복/1244.cpp
> +	}
👍👍👍

2021-10-11 09:26 UTC, bsa0322 commented on 10월 5일 - 분할 정복/17281.cpp
> +			start_player = 1;
p1. 이미 겉에 while문이 돌고 있네요! 그렇다면 타자 순서를 for문으로 처리해 주지 않고 변수 하나로 처리할 수 있지 않을까요? 더불어 이렇게 되면 3번 아웃 시 바로 break를 걸어서 next_inning변수 사용도 없어지겠네요~!

2021-10-11 09:26 UTC, bsa0322 commented on 10월 5일 - 분할 정복/17281.cpp
> +	result = (score > result ? score : result);
p3. 삼항 연산자는 가독성 등의 이유로 사용을 최대한 피하는 게 좋아요! 둘 중 더 큰 값을 선택하는 더 직관적인 함수가 있죠!

2021-10-11 09:26 UTC, bsa0322 commented on 10월 5일 - 분할 정복/17281.cpp
> +}
오,,,cnt를 선수 번호로 하고, i를 타자 번호로 설정하셨군요!! (저는 이거랑 반대로 해서 cnt == 4일때 넘겨주는 코드가 하나 더 추가됐어야 했거든여 허헣) 아주 좋아요!! 👍👍👍

2021-10-11 09:26 UTC, bsa0322 commented on 10월 5일 - 분할 정복/17829.cpp
> +	result[3] = x[i + 1][j + 1];
p2. 반복문 사용으로 더 간단하게 리팩토링 해볼까요!

2021-10-11 09:26 UTC, bsa0322 commented on 10월 5일 - 분할 정복/17829.cpp
> +}
p3. 👍👍 더불어 샘플코드는 4등분씩 분할하다가 4개의 원소 중 2번째로 큰 수만 골라서 2 * 2크기를 유지하는 방식으로 풀이하였으니 나중에 확인해보셔도 좋을 것 같아요!

2021-10-11 09:26 UTC, bsa0322 commented on 10월 5일 - 분할 정복/2447.cpp
> +	}
p2. 현재 위치마다 최소 분할된 구간에서 별의 위치인지, 공백의 위치인지 확인하는 풀이로 풀어주셨네요!!!! 그것도 좋지만 지금 메인에서 O(n^2)의 시간복잡도에 여기서 계속 별을 쪼개니 시간이 다소 걸릴거예요.
별을 자세히 보시면 지금 9개의 구간으로 계속 나눌 수 있죠! 그리고 9개의 구간 중 가운데 구간이 공백이에요. 이를 활용해서 9등분씩 분할하다가 공백 구간만 제외하고 별을 채우는 방식으로 풀면 어떨까요?

2021-10-11 14:02 UTC, bsa0322 approved these changes
수정하신 부분 모두 확인했습니다! 아주 좋아요. 머지해주셔도 괜찮아요! 수고하셨습니다~! 👍

2021-10-12 07:19 UTC, jaeseo222 commented
싸랑합니당💨💨

2021-10-12 07:20 UTC, merged