[스택, 큐, 덱] 9월 15일
Altu-Bitu/Altu-Bitu_jaeseo pull request #5
Opened 2021-09-15 09:11 UTC by jaeseo222

2021-09-15 13:14 UTC, HyunJiLim0406 reviewed
p3
수고하셨습니다! 논리나 시간복잡도면에서는 드릴 조언이 없는 코드들입니다.
함수화 할 수 있는 부분들도 많이 잡아내셨네요!
다만, 가독성면에서 약간 아쉬운 부분들이 사알짝 있어요! 조금만 수정하고 merge할까요?
코드를 다 짜신 뒤에 한번 살펴보며 더 함수화 할 수 있는 곳은 없는지, 비효율적인 부분은 없는지 등등을 살펴보는 것도 좋아요!
수정하시고 리뷰어로 저 호출해주세요~

2021-09-15 13:14 UTC, HyunJiLim0406 commented on 9월 10일 - 스택, 큐, 덱/1918.cpp
> +		case '(': s.push('('); break;
일관성을 유지하려면 s.push(str[i])이 좋아요!

2021-09-15 13:14 UTC, HyunJiLim0406 commented on 9월 10일 - 스택, 큐, 덱/1918.cpp
> +}
오 재미있는 함수를 사용하셨네요!
근데 이렇게 봐서는 조건문이 뭘 의미하는지 알기 힘들어요. 연산자의 우선순위를 리턴하는 함수로 바꿔보는건 어떨까요?

2021-09-15 13:14 UTC, HyunJiLim0406 commented on 9월 10일 - 스택, 큐, 덱/1935.cpp
> +		}
아주 잘 끊으셨습니다!

2021-09-15 13:14 UTC, HyunJiLim0406 commented on 9월 10일 - 스택, 큐, 덱/1935.cpp
> +		}
이 부분을 연산결과를 리턴하는 함수로 만들어도 좋아요~

2021-09-15 13:14 UTC, HyunJiLim0406 commented on 9월 10일 - 스택, 큐, 덱/2019 카카오 개발자 겨울 인턴십.cpp
> +				if (!s.empty() && s.top() == board[j][check])
인덴테이션이 너무 깊게 들어가네요...!
열마다의 인형 상태를 스택에 넣는 전처리를 하면 어떨까요?

2021-09-15 13:14 UTC, HyunJiLim0406 commented on 9월 10일 - 스택, 큐, 덱/20920.cpp
> +	sort(voca.begin(), voca.end(), cmp);// 정렬된 단어장
맵을 바로 벡터에 넣으셨네요! 좋은 전략입니다

2021-09-15 13:14 UTC, HyunJiLim0406 commented on 9월 10일 - 스택, 큐, 덱/5430.cpp
> +}
함수로 잘 빼셨어요! 이 함수가 덱을 리턴해도 좋을 것 같아요!

2021-09-15 13:14 UTC, HyunJiLim0406 commented on 9월 10일 - 스택, 큐, 덱/5430.cpp
> +}
여기도 함수화 하신 건 너무 좋지만, void보다는 뭔갈 리턴하는게 좋아요!

2021-09-16 03:20 UTC, HyunJiLim0406 requested changes
p1
다 잘 수정해주셨습니다! 근데 지금 크레인 문제에서 런타임에러가 발생할 수도 있을 것 같은 부분이 보여요...! 확인해주시고 다시 리뷰어로 저 호출해주세요!!

2021-09-16 03:20 UTC, HyunJiLim0406 commented on 9월 10일 - 스택, 큐, 덱/1918.cpp
> +}
힌트를 더 드리자면...! 이 함수가 bool 말고 int를 리턴하도록 하면 어떨까요? 그렇다면 이 함수는 어떤 인자에 대해 어떤 것들을 리턴하게 될까요?

2021-09-16 03:20 UTC, HyunJiLim0406 commented on 9월 10일 - 스택, 큐, 덱/1935.cpp
> +}
아주 좋아요!

2021-09-16 03:20 UTC, HyunJiLim0406 commented on 9월 10일 - 스택, 큐, 덱/2019 카카오 개발자 겨울 인턴십.cpp
> +		}//[]때문에 말썽,,
board[j][i]는 항상 숫자 아닐까요?

2021-09-16 03:20 UTC, HyunJiLim0406 commented on 9월 10일 - 스택, 큐, 덱/2019 카카오 개발자 겨울 인턴십.cpp
> +		col[moves[i] - 1].pop();
p1
제가 제대로 이해하지 못한걸수도 있는데 이부분 코드가 위험해보여요
위에서 0이 아닌것만 col 스택에 넣었는데 0을 체크하는게 의미가 있을까요? 그리고 col에 대한 empty 체크가 없어보입니다..! 여기 꼭 수정하셔야 해요
혹시 제가 뭔갈 잘못 이해한거라면 말해주세요!!

2021-09-16 03:20 UTC, HyunJiLim0406 commented on 9월 10일 - 스택, 큐, 덱/5430.cpp
> +		dq = operation(dq, fun, funR, error);
좋아요~

2021-09-20 06:20 UTC, HyunJiLim0406 requested changes
p1
허허 pr이 섞였네요! 브랜치를 분리하거나 이전 pr을 머지하는 방법으로 겹치지 않게 해주세요!
전반적으로 아주 잘 푸셨어요! 11286번만 살짝 수정해볼까요?

수정 후 리뷰어로 저 호출해주세요~

추석 잘 보내세요 재서님!

2021-09-20 06:20 UTC, HyunJiLim0406 commented on 9월 14일 - 우선순위 큐/11000.cpp
> +	cout << pq.size();
👍

2021-09-20 06:20 UTC, HyunJiLim0406 commented on 9월 14일 - 우선순위 큐/11286.cpp
> +
p1
핳 사실 이 문제는 정렬의 compare 함수처럼 우선순위 큐에서의 compare 함수를 정의하는 연습을 위한 문제였습니다!
abs(x)를 따로 저장하지 않고 풀어볼까요?

2021-09-20 06:20 UTC, HyunJiLim0406 commented on 9월 14일 - 우선순위 큐/11723.cpp
> +	bool s[21] = {false}; //20개의 숫자에 체크/언체크
잘 푸셨습니다~
근데 이거랑 같은 논리로 배열없이 풀 수 있는 방법이 있어요!
비트마스킹이라는 방법인데요. 이건 좀 어려울 수도 있으니까 알아만 보셔도 좋아요~

2021-09-20 06:20 UTC, HyunJiLim0406 commented on 9월 14일 - 우선순위 큐/3613.cpp
> +	}
좋아요! 알파벳 체크에서는 isupper 함수를 쓸 수도 있겠네요!

2021-09-20 06:20 UTC, HyunJiLim0406 commented on 9월 14일 - 우선순위 큐/3613.cpp
> +}
얘네가 그냥 string을 리턴하는게 좋아요~!

2021-09-20 06:20 UTC, HyunJiLim0406 commented on 9월 14일 - 우선순위 큐/3613.cpp
> +int main() {
지금 언어 체크하는 코드도 좋지만 cppToJava나 javaToCpp 함수처럼 함수를 따로 만드는 것도 좋아요~

2021-09-20 06:20 UTC, HyunJiLim0406 commented on 9월 14일 - 우선순위 큐/7662.cpp
> +
잘 사용하셨어요! 멀티셋없이 우선순위 큐로만 푸는 풀이도 고민해보세요~

2021-09-21 19:23 UTC, jaeseo222 commented
제가 코멘트를 달아도 되는 지 모르겠지만,,, 튜터님 모두 연휴 동안에도 정성 가득한 피드백 해주셔서 너무 감사드려요!!
특히 저의 부족한 코드를.......... 봐주신 ....... 현지님 정말 감사드립니다..! 😭😭
덕분에 새로운 함수도 알게됐고, 튜터님께서 올려주신 (진짜 쩌는.. )풀이를 참고하여 로직을 생각해 볼 수 있었습니다. 핳ㅎ><
그럼 연휴 즐겁게 보내셨길, 그리고 앞으로도 즐거운 시간만 보내시길 바랍니다!!

2021-09-22 04:16 UTC, HyunJiLim0406 reviewed
p3
하핳 감사합니다...!
부족하다니요! 저희도 코드리뷰를 하면서 다양한 분들의 코드를 볼 수 있고, 그 과정에서 많이 배우고 있어요~
이제 머지하셔도 됩니다! 연휴가 하루남았네요! 마지막 날까지 즐거운 한가위 되세요!

2021-09-22 07:15 UTC, merged